server:
  port: 8888

team:
  name: Web2班
  leader: zhz
  phone: 18061657605
  age: 6

spring:
  servlet:
    multipart:
      max-file-size: 10MB # 单个上传文件大小限定为10M，默认值为1M
      max-request-size: 100MB # 单次上传文件大小限定为100M，默认值为10M
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1967430835@qq.com #你的qq邮箱
    password: fpailvzfmawidcbe #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Spring Boot #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

custom:
  qrcode:
    content: "http://www.baidu.com"