server:
  port: 8888
spring:
  application:
    name: quickstart

my:
  mood:
    today: "星期五"
    content: "今天心情不错"
    author: zhz

    feature:
      helloSwitch: true
      closeMsg: "该接口正在维护,10分钟后再来吧!"

zhz:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSid: 2c94811c9860a9c4019917b778cd1d9c
      accountToken: 0da43c36bb084b3e8f58c9b11678609e
      appId: 2c94811c9860a9c4019917b77a291da3
      templateId: 1