server:
  port: 8888
spring:
  application:
    name: quickstart

my:
  mood:
    today: "星期五"
    content: "今天心情不错"
    author: zhz

    feature:
      helloSwitch: true
      closeMsg: "该接口正在维护,10分钟后再来吧!"